import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../models/local_track.dart';
import '../../services/library_controller.dart';
import '../../services/playback_controller.dart';
import '../../services/catalog_controller.dart';
import '../widgets/track_artwork.dart';
import '../widgets/track_tile.dart';

class HomeScreen extends StatelessWidget { const HomeScreen({super.key});
  @override Widget build(BuildContext context) { final l = context.watch<LibraryController>(); final catalog = context.watch<CatalogController>(); if (l.loading) return const Center(child: CircularProgressIndicator()); if (l.tracks.isEmpty) { catalog.loadHome(); return _OnlineHome(catalog: catalog); } final favorites = l.tracks.where((t) => l.favorites.contains(t.id)).toList(); return SafeArea(child: CustomScrollView(slivers: [const SliverPadding(padding: EdgeInsets.fromLTRB(20, 24, 20, 8), sliver: SliverToBoxAdapter(child: Text('Good evening', style: TextStyle(fontSize: 34, fontWeight: FontWeight.w700, letterSpacing: -1))), SliverToBoxAdapter(child: _Rail(title: 'Recently played', tracks: l.recent, queue: l.recent)), if (favorites.isNotEmpty) SliverToBoxAdapter(child: _Rail(title: 'Favorites', tracks: favorites, queue: favorites)), SliverToBoxAdapter(child: Padding(padding: const EdgeInsets.fromLTRB(20, 28, 20, 8), child: Text('Recently added', style: Theme.of(context).textTheme.titleLarge)), SliverList(delegate: SliverChildBuilderDelegate((_, i) => TrackTile(track: l.tracks[i], queue: l.tracks), childCount: l.tracks.length))])); }
}
class _OnlineHome extends StatelessWidget { const _OnlineHome({required this.catalog}); final CatalogController catalog; @override Widget build(BuildContext context) => SafeArea(child: ListView(padding: const EdgeInsets.fromLTRB(20, 24, 20, 120), children: [Text('Aurora', style: Theme.of(context).textTheme.displaySmall), const SizedBox(height: 8), Text('Explore ${catalog.providerName}', style: TextStyle(color: Colors.white.withValues(alpha: .62))), const SizedBox(height: 28), if (catalog.loading) const Center(child: CircularProgressIndicator()), if (catalog.error != null) _Empty(title: 'Unable to load music', detail: catalog.error!, action: 'Try again', onTap: catalog.loadHome), if (catalog.featured.isNotEmpty) Text('Featured open music', style: Theme.of(context).textTheme.titleLarge), const SizedBox(height: 12), ...catalog.featured.map((track) => ListTile(leading: const CircleAvatar(child: Icon(Icons.music_note_rounded)), title: Text(track.title, maxLines: 1, overflow: TextOverflow.ellipsis), subtitle: Text(track.artist, maxLines: 1, overflow: TextOverflow.ellipsis), trailing: const Icon(Icons.play_arrow_rounded), onTap: () => context.read<PlaybackController>().playCatalog(catalog.featured, catalog.featured.indexOf(track))))])); }
class _Rail extends StatelessWidget { const _Rail({required this.title, required this.tracks, required this.queue}); final String title; final List<LocalTrack> tracks, queue; @override Widget build(BuildContext context) { if (tracks.isEmpty) return const SizedBox.shrink(); return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: const EdgeInsets.fromLTRB(20, 28, 20, 12), child: Text(title, style: Theme.of(context).textTheme.titleLarge)), SizedBox(height: 156, child: ListView.separated(scrollDirection: Axis.horizontal, padding: const EdgeInsets.symmetric(horizontal: 20), itemCount: tracks.length > 12 ? 12 : tracks.length, separatorBuilder: (_, __) => const SizedBox(width: 14), itemBuilder: (_, i) { final t = tracks[i]; return SizedBox(width: 112, child: InkWell(borderRadius: BorderRadius.circular(14), onTap: () { context.read<LibraryController>().markPlayed(t.id); context.read<PlaybackController>().play(queue, queue.indexOf(t)); }, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [TrackArtwork(id: t.id, size: 112, radius: 14), const SizedBox(height: 6), Text(t.title, maxLines: 1, overflow: TextOverflow.ellipsis, style: const TextStyle(fontWeight: FontWeight.w600))])); }))]); } }
class _Empty extends StatelessWidget { const _Empty({required this.title, required this.detail, required this.action, required this.onTap}); final String title, detail, action; final VoidCallback onTap; @override Widget build(BuildContext context) => Center(child: Padding(padding: const EdgeInsets.all(38), child: Column(mainAxisSize: MainAxisSize.min, children: [const Icon(Icons.library_music_outlined, size: 52), const SizedBox(height: 18), Text(title, style: Theme.of(context).textTheme.titleLarge), const SizedBox(height: 8), Text(detail, textAlign: TextAlign.center, style: TextStyle(color: Colors.white.withValues(alpha: .6))), const SizedBox(height: 18), FilledButton(onPressed: onTap, child: Text(action))]))); }
