import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../services/library_controller.dart';
import '../widgets/track_tile.dart';

class LibraryScreen extends StatefulWidget { const LibraryScreen({super.key}); @override State<LibraryScreen> createState() => _LibraryScreenState(); }
class _LibraryScreenState extends State<LibraryScreen> { var tab = 0; final labels = const ['Songs', 'Albums', 'Artists', 'Playlists', 'Favorites'];
  @override Widget build(BuildContext context) { final l = context.watch<LibraryController>(); final favorites = l.tracks.where((t) => l.favorites.contains(t.id)).toList(); return SafeArea(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Padding(padding: EdgeInsets.fromLTRB(20, 24, 20, 8), child: Text('Library', style: TextStyle(fontSize: 34, fontWeight: FontWeight.w700, letterSpacing: -1))), SizedBox(height: 44, child: ListView.separated(scrollDirection: Axis.horizontal, padding: const EdgeInsets.symmetric(horizontal: 20), itemCount: labels.length, separatorBuilder: (_, __) => const SizedBox(width: 8), itemBuilder: (_, i) => ChoiceChip(label: Text(labels[i]), selected: tab == i, onSelected: (_) => setState(() => tab = i)))), const SizedBox(height: 8), Expanded(child: tab == 3 ? _Playlists(l: l) : tab == 1 || tab == 2 ? _Groups(kind: tab == 1 ? 'Albums' : 'Artists', groups: tab == 1 ? l.tracks.map((t) => t.album).toSet() : l.tracks.map((t) => t.artist).toSet()) : ListView.builder(itemCount: tab == 4 ? favorites.length : l.tracks.length, itemBuilder: (_, i) { final list = tab == 4 ? favorites : l.tracks; return TrackTile(track: list[i], queue: list); }))])); }
}
class _Groups extends StatelessWidget { const _Groups({required this.kind, required this.groups}); final String kind; final Set<String> groups; @override Widget build(BuildContext context) => ListView(children: [for (final item in groups) ListTile(leading: const CircleAvatar(child: Icon(Icons.album_outlined)), title: Text(item), subtitle: Text(kind.substring(0, kind.length - 1)))]); }
class _Playlists extends StatelessWidget { const _Playlists({required this.l}); final LibraryController l; @override Widget build(BuildContext context) => ListView(children: [ListTile(leading: const CircleAvatar(child: Icon(Icons.add_rounded)), title: const Text('New playlist'), onTap: () async { final name = await _name(context, 'New playlist'); if (name != null && name.trim().isNotEmpty) l.createPlaylist(name.trim()); }), ...l.playlists.map((p) => ListTile(leading: const CircleAvatar(child: Icon(Icons.queue_music_rounded)), title: Text(p.name), subtitle: Text('${p.trackIds.length} songs'), trailing: PopupMenuButton<String>(onSelected: (action) async { if (action == 'delete') l.deletePlaylist(p.id); else { final name = await _name(context, 'Rename playlist', p.name); if (name != null && name.trim().isNotEmpty) l.renamePlaylist(p.id, name.trim()); } }, itemBuilder: (_) => const [PopupMenuItem(value: 'rename', child: Text('Rename')), PopupMenuItem(value: 'delete', child: Text('Delete'))])))]); }
Future<String?> _name(BuildContext context, String label, [String initial = '']) { final c = TextEditingController(text: initial); return showDialog<String>(context: context, builder: (_) => AlertDialog(title: Text(label), content: TextField(controller: c, autofocus: true, decoration: const InputDecoration(hintText: 'Name')), actions: [TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')), FilledButton(onPressed: () => Navigator.pop(context, c.text), child: const Text('Save'))])); }
