import 'package:flutter/material.dart';
import 'package:just_audio/just_audio.dart';
import 'package:provider/provider.dart';
import '../../services/library_controller.dart';
import '../../services/playback_controller.dart';
import '../widgets/track_artwork.dart';

class NowPlayingScreen extends StatelessWidget { const NowPlayingScreen({super.key});
  @override Widget build(BuildContext context) { final p = context.watch<PlaybackController>(); final t = p.current; if (t == null) return const Scaffold(body: Center(child: Text('Nothing is playing'))); final liked = context.watch<LibraryController>().favorites.contains(t.id); return Scaffold(body: SafeArea(child: Padding(padding: const EdgeInsets.symmetric(horizontal: 24), child: Column(children: [Align(alignment: Alignment.centerLeft, child: IconButton(onPressed: () => Navigator.pop(context), icon: const Icon(Icons.keyboard_arrow_down_rounded))), const Spacer(), Hero(tag: 'art-${t.id}', child: TrackArtwork(id: t.id, size: MediaQuery.of(context).size.width - 48, radius: 24)), const SizedBox(height: 28), Row(children: [Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(t.title, style: Theme.of(context).textTheme.titleLarge, maxLines: 1, overflow: TextOverflow.ellipsis), const SizedBox(height: 4), Text('${t.artist} · ${t.album}', style: TextStyle(color: Colors.white.withValues(alpha: .6)), maxLines: 1, overflow: TextOverflow.ellipsis)])), IconButton(onPressed: () => context.read<LibraryController>().toggleFavorite(t.id), icon: Icon(liked ? Icons.favorite_rounded : Icons.favorite_border_rounded, color: liked ? Theme.of(context).colorScheme.primary : null))]), const SizedBox(height: 16), StreamBuilder<Duration>(stream: p.position, builder: (_, snap) { final pos = snap.data ?? Duration.zero; return StreamBuilder<Duration?>(stream: p.duration, builder: (_, dur) { final total = dur.data ?? t.duration; return Column(children: [Slider(value: pos.inMilliseconds.clamp(0, total.inMilliseconds).toDouble(), max: total.inMilliseconds.toDouble().clamp(1, double.infinity), onChanged: (v) => p.seek(Duration(milliseconds: v.round()))), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(_time(pos)), Text('-${_time(total - pos)}')])]); }); }), Row(mainAxisAlignment: MainAxisAlignment.spaceAround, children: [IconButton(onPressed: p.toggleShuffle, icon: Icon(Icons.shuffle_rounded, color: p.shuffle ? Theme.of(context).colorScheme.primary : null)), IconButton(iconSize: 38, onPressed: p.previous, icon: const Icon(Icons.skip_previous_rounded)), FilledButton(onPressed: p.toggle, style: FilledButton.styleFrom(shape: const CircleBorder(), padding: const EdgeInsets.all(17)), child: Icon(p.playing ? Icons.pause_rounded : Icons.play_arrow_rounded, size: 36)), IconButton(iconSize: 38, onPressed: p.next, icon: const Icon(Icons.skip_next_rounded)), IconButton(onPressed: p.cycleRepeat, icon: Icon(Icons.repeat_rounded, color: p.loopMode == LoopMode.off ? null : Theme.of(context).colorScheme.primary))]), const Spacer()]))); }
  String _time(Duration d) => '${d.inMinutes}:${(d.inSeconds % 60).toString().padLeft(2, '0')}';
}
